/*
 * This file is generated by jOOQ.
*/
package com.luzhiqing.bamboo.entity.tables;


import com.luzhiqing.bamboo.entity.BambooAuth;
import com.luzhiqing.bamboo.entity.Indexes;
import com.luzhiqing.bamboo.entity.Keys;
import com.luzhiqing.bamboo.entity.tables.records.TAuthSysRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UShort;

import javax.annotation.Generated;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;


/**
 * 系统map(登记目前存在的后台系统信息)
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class T_AUTH_SYS extends TableImpl<TAuthSysRecord> {

    private static final long serialVersionUID = 1294348141;

    /**
     * The reference instance of <code>bamboo_auth.t_auth_sys</code>
     */
    public static final T_AUTH_SYS T_AUTH_SYS = new T_AUTH_SYS();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TAuthSysRecord> getRecordType() {
        return TAuthSysRecord.class;
    }

    /**
     * The column <code>bamboo_auth.t_auth_sys.id</code>. 自增id
     */
    public final TableField<TAuthSysRecord, UShort> ID = createField("id", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED.nullable(false).identity(true), this, "自增id");

    /**
     * The column <code>bamboo_auth.t_auth_sys.sys_name</code>. 系统名称
     */
    public final TableField<TAuthSysRecord, String> SYS_NAME = createField("sys_name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "系统名称");

    /**
     * The column <code>bamboo_auth.t_auth_sys.sys_desc</code>. 系统描述
     */
    public final TableField<TAuthSysRecord, String> SYS_DESC = createField("sys_desc", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "系统描述");

    /**
     * The column <code>bamboo_auth.t_auth_sys.sys_domain</code>. 系统域名
     */
    public final TableField<TAuthSysRecord, String> SYS_DOMAIN = createField("sys_domain", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "系统域名");

    /**
     * The column <code>bamboo_auth.t_auth_sys.create_time</code>.
     */
    public final TableField<TAuthSysRecord, LocalDateTime> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>bamboo_auth.t_auth_sys.create_user</code>.
     */
    public final TableField<TAuthSysRecord, Integer> CREATE_USER = createField("create_user", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>bamboo_auth.t_auth_sys.create_user_name</code>.
     */
    public final TableField<TAuthSysRecord, String> CREATE_USER_NAME = createField("create_user_name", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>bamboo_auth.t_auth_sys.update_time</code>.
     */
    public final TableField<TAuthSysRecord, LocalDateTime> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>bamboo_auth.t_auth_sys.update_user</code>.
     */
    public final TableField<TAuthSysRecord, Integer> UPDATE_USER = createField("update_user", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>bamboo_auth.t_auth_sys.update_user_name</code>.
     */
    public final TableField<TAuthSysRecord, String> UPDATE_USER_NAME = createField("update_user_name", org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>bamboo_auth.t_auth_sys.delete_time</code>.
     */
    public final TableField<TAuthSysRecord, LocalDateTime> DELETE_TIME = createField("delete_time", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>bamboo_auth.t_auth_sys.delete_user</code>.
     */
    public final TableField<TAuthSysRecord, Integer> DELETE_USER = createField("delete_user", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>bamboo_auth.t_auth_sys.delete_user_name</code>.
     */
    public final TableField<TAuthSysRecord, String> DELETE_USER_NAME = createField("delete_user_name", org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>bamboo_auth.t_auth_sys.enabled</code>.
     */
    public final TableField<TAuthSysRecord, Boolean> ENABLED = createField("enabled", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.inline("1", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * Create a <code>bamboo_auth.t_auth_sys</code> table reference
     */
    public T_AUTH_SYS() {
        this(DSL.name("t_auth_sys"), null);
    }

    /**
     * Create an aliased <code>bamboo_auth.t_auth_sys</code> table reference
     */
    public T_AUTH_SYS(String alias) {
        this(DSL.name(alias), T_AUTH_SYS);
    }

    /**
     * Create an aliased <code>bamboo_auth.t_auth_sys</code> table reference
     */
    public T_AUTH_SYS(Name alias) {
        this(alias, T_AUTH_SYS);
    }

    private T_AUTH_SYS(Name alias, Table<TAuthSysRecord> aliased) {
        this(alias, aliased, null);
    }

    private T_AUTH_SYS(Name alias, Table<TAuthSysRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "系统map(登记目前存在的后台系统信息)");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BambooAuth.BAMBOO_AUTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_AUTH_SYS_IDX_DOMAIN, Indexes.T_AUTH_SYS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TAuthSysRecord, UShort> getIdentity() {
        return Keys.IDENTITY_T_AUTH_SYS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TAuthSysRecord> getPrimaryKey() {
        return Keys.KEY_T_AUTH_SYS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TAuthSysRecord>> getKeys() {
        return Arrays.<UniqueKey<TAuthSysRecord>>asList(Keys.KEY_T_AUTH_SYS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_AUTH_SYS as(String alias) {
        return new T_AUTH_SYS(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_AUTH_SYS as(Name alias) {
        return new T_AUTH_SYS(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public T_AUTH_SYS rename(String name) {
        return new T_AUTH_SYS(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public T_AUTH_SYS rename(Name name) {
        return new T_AUTH_SYS(name, null);
    }
}
