/*
 * This file is generated by jOOQ.
*/
package com.luzhiqing.bamboo.entity.tables;


import com.luzhiqing.bamboo.entity.BambooAuth;
import com.luzhiqing.bamboo.entity.Indexes;
import com.luzhiqing.bamboo.entity.Keys;
import com.luzhiqing.bamboo.entity.tables.records.TAuthSysMenuRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;

import javax.annotation.Generated;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;


/**
 * 系统menu
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class T_AUTH_SYS_MENU extends TableImpl<TAuthSysMenuRecord> {

    private static final long serialVersionUID = -493966156;

    /**
     * The reference instance of <code>bamboo_auth.t_auth_sys_menu</code>
     */
    public static final T_AUTH_SYS_MENU T_AUTH_SYS_MENU = new T_AUTH_SYS_MENU();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TAuthSysMenuRecord> getRecordType() {
        return TAuthSysMenuRecord.class;
    }

    /**
     * The column <code>bamboo_auth.t_auth_sys_menu.id</code>. 自增id
     */
    public final TableField<TAuthSysMenuRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "自增id");

    /**
     * The column <code>bamboo_auth.t_auth_sys_menu.sys_id</code>. 系统id
     */
    public final TableField<TAuthSysMenuRecord, UShort> SYS_ID = createField("sys_id", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED.nullable(false).defaultValue(DSL.inline("0", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED)), this, "系统id");

    /**
     * The column <code>bamboo_auth.t_auth_sys_menu.parent_id</code>. 父菜单id
     */
    public final TableField<TAuthSysMenuRecord, UInteger> PARENT_ID = createField("parent_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(DSL.inline("0", org.jooq.impl.SQLDataType.INTEGERUNSIGNED)), this, "父菜单id");

    /**
     * The column <code>bamboo_auth.t_auth_sys_menu.menu_name</code>. 菜单名称
     */
    public final TableField<TAuthSysMenuRecord, String> MENU_NAME = createField("menu_name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "菜单名称");

    /**
     * The column <code>bamboo_auth.t_auth_sys_menu.menu_desc</code>. 菜单描述
     */
    public final TableField<TAuthSysMenuRecord, String> MENU_DESC = createField("menu_desc", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "菜单描述");

    /**
     * The column <code>bamboo_auth.t_auth_sys_menu.menu_uri</code>. 菜单uri
     */
    public final TableField<TAuthSysMenuRecord, String> MENU_URI = createField("menu_uri", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.inline("0", org.jooq.impl.SQLDataType.VARCHAR)), this, "菜单uri");

    /**
     * The column <code>bamboo_auth.t_auth_sys_menu.showing</code>. 是否展示菜单
     */
    public final TableField<TAuthSysMenuRecord, Byte> SHOWING = createField("showing", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "是否展示菜单");

    /**
     * The column <code>bamboo_auth.t_auth_sys_menu.create_time</code>.
     */
    public final TableField<TAuthSysMenuRecord, LocalDateTime> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>bamboo_auth.t_auth_sys_menu.create_user</code>.
     */
    public final TableField<TAuthSysMenuRecord, Integer> CREATE_USER = createField("create_user", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>bamboo_auth.t_auth_sys_menu.create_user_name</code>.
     */
    public final TableField<TAuthSysMenuRecord, String> CREATE_USER_NAME = createField("create_user_name", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>bamboo_auth.t_auth_sys_menu.update_time</code>.
     */
    public final TableField<TAuthSysMenuRecord, LocalDateTime> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>bamboo_auth.t_auth_sys_menu.update_user</code>.
     */
    public final TableField<TAuthSysMenuRecord, Integer> UPDATE_USER = createField("update_user", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>bamboo_auth.t_auth_sys_menu.update_user_name</code>.
     */
    public final TableField<TAuthSysMenuRecord, String> UPDATE_USER_NAME = createField("update_user_name", org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>bamboo_auth.t_auth_sys_menu.delete_time</code>.
     */
    public final TableField<TAuthSysMenuRecord, LocalDateTime> DELETE_TIME = createField("delete_time", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>bamboo_auth.t_auth_sys_menu.delete_user</code>.
     */
    public final TableField<TAuthSysMenuRecord, Integer> DELETE_USER = createField("delete_user", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>bamboo_auth.t_auth_sys_menu.delete_user_name</code>.
     */
    public final TableField<TAuthSysMenuRecord, String> DELETE_USER_NAME = createField("delete_user_name", org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>bamboo_auth.t_auth_sys_menu.enabled</code>.
     */
    public final TableField<TAuthSysMenuRecord, Boolean> ENABLED = createField("enabled", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.inline("1", org.jooq.impl.SQLDataType.BOOLEAN)), this, "");

    /**
     * Create a <code>bamboo_auth.t_auth_sys_menu</code> table reference
     */
    public T_AUTH_SYS_MENU() {
        this(DSL.name("t_auth_sys_menu"), null);
    }

    /**
     * Create an aliased <code>bamboo_auth.t_auth_sys_menu</code> table reference
     */
    public T_AUTH_SYS_MENU(String alias) {
        this(DSL.name(alias), T_AUTH_SYS_MENU);
    }

    /**
     * Create an aliased <code>bamboo_auth.t_auth_sys_menu</code> table reference
     */
    public T_AUTH_SYS_MENU(Name alias) {
        this(alias, T_AUTH_SYS_MENU);
    }

    private T_AUTH_SYS_MENU(Name alias, Table<TAuthSysMenuRecord> aliased) {
        this(alias, aliased, null);
    }

    private T_AUTH_SYS_MENU(Name alias, Table<TAuthSysMenuRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "系统menu");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BambooAuth.BAMBOO_AUTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_AUTH_SYS_MENU_IDX_PARENT_ID, Indexes.T_AUTH_SYS_MENU_IDX_SYS_ID, Indexes.T_AUTH_SYS_MENU_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TAuthSysMenuRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_T_AUTH_SYS_MENU;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TAuthSysMenuRecord> getPrimaryKey() {
        return Keys.KEY_T_AUTH_SYS_MENU_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TAuthSysMenuRecord>> getKeys() {
        return Arrays.<UniqueKey<TAuthSysMenuRecord>>asList(Keys.KEY_T_AUTH_SYS_MENU_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_AUTH_SYS_MENU as(String alias) {
        return new T_AUTH_SYS_MENU(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public T_AUTH_SYS_MENU as(Name alias) {
        return new T_AUTH_SYS_MENU(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public T_AUTH_SYS_MENU rename(String name) {
        return new T_AUTH_SYS_MENU(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public T_AUTH_SYS_MENU rename(Name name) {
        return new T_AUTH_SYS_MENU(name, null);
    }
}
