server:
  port: 8081
spring:
  application:
    name: bamboo-auth-server
  datasource:
    url: jdbc:mysql://39.107.239.107:3306/bamboo_auth
    username: root
    password: 7416kobe!
    driver-class-name: com.mysql.jdbc.Driver
  jooq:
    sql-dialect: mysql
  session:
    store-type: none
  flyway:
    baseline-on-migrate: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://39.107.239.107:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  config: classpath:log4j2.xml
