/*
 * This file is generated by jOOQ.
*/
package com.luzhiqing.bamboo.entity.tables.records;


import com.luzhiqing.bamboo.entity.tables.T_AUTH_SYS;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UShort;

import javax.annotation.Generated;
import java.time.LocalDateTime;


/**
 * 系统map(登记目前存在的后台系统信息)
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAuthSysRecord extends UpdatableRecordImpl<TAuthSysRecord> implements Record14<UShort, String, String, String, LocalDateTime, Integer, String, LocalDateTime, Integer, String, LocalDateTime, Integer, String, Boolean> {

    private static final long serialVersionUID = 1047844194;

    /**
     * Setter for <code>bamboo_auth.t_auth_sys.id</code>. 自增id
     */
    public void setId(UShort value) {
        set(0, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_auth_sys.id</code>. 自增id
     */
    public UShort getId() {
        return (UShort) get(0);
    }

    /**
     * Setter for <code>bamboo_auth.t_auth_sys.sys_name</code>. 系统名称
     */
    public void setSysName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_auth_sys.sys_name</code>. 系统名称
     */
    public String getSysName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bamboo_auth.t_auth_sys.sys_desc</code>. 系统描述
     */
    public void setSysDesc(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_auth_sys.sys_desc</code>. 系统描述
     */
    public String getSysDesc() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bamboo_auth.t_auth_sys.sys_domain</code>. 系统域名
     */
    public void setSysDomain(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_auth_sys.sys_domain</code>. 系统域名
     */
    public String getSysDomain() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bamboo_auth.t_auth_sys.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_auth_sys.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>bamboo_auth.t_auth_sys.create_user</code>.
     */
    public void setCreateUser(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_auth_sys.create_user</code>.
     */
    public Integer getCreateUser() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>bamboo_auth.t_auth_sys.create_user_name</code>.
     */
    public void setCreateUserName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_auth_sys.create_user_name</code>.
     */
    public String getCreateUserName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>bamboo_auth.t_auth_sys.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_auth_sys.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>bamboo_auth.t_auth_sys.update_user</code>.
     */
    public void setUpdateUser(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_auth_sys.update_user</code>.
     */
    public Integer getUpdateUser() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>bamboo_auth.t_auth_sys.update_user_name</code>.
     */
    public void setUpdateUserName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_auth_sys.update_user_name</code>.
     */
    public String getUpdateUserName() {
        return (String) get(9);
    }

    /**
     * Setter for <code>bamboo_auth.t_auth_sys.delete_time</code>.
     */
    public void setDeleteTime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_auth_sys.delete_time</code>.
     */
    public LocalDateTime getDeleteTime() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>bamboo_auth.t_auth_sys.delete_user</code>.
     */
    public void setDeleteUser(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_auth_sys.delete_user</code>.
     */
    public Integer getDeleteUser() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>bamboo_auth.t_auth_sys.delete_user_name</code>.
     */
    public void setDeleteUserName(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_auth_sys.delete_user_name</code>.
     */
    public String getDeleteUserName() {
        return (String) get(12);
    }

    /**
     * Setter for <code>bamboo_auth.t_auth_sys.enabled</code>.
     */
    public void setEnabled(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_auth_sys.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UShort> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<UShort, String, String, String, LocalDateTime, Integer, String, LocalDateTime, Integer, String, LocalDateTime, Integer, String, Boolean> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<UShort, String, String, String, LocalDateTime, Integer, String, LocalDateTime, Integer, String, LocalDateTime, Integer, String, Boolean> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UShort> field1() {
        return T_AUTH_SYS.T_AUTH_SYS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return T_AUTH_SYS.T_AUTH_SYS.SYS_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return T_AUTH_SYS.T_AUTH_SYS.SYS_DESC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return T_AUTH_SYS.T_AUTH_SYS.SYS_DOMAIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field5() {
        return T_AUTH_SYS.T_AUTH_SYS.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return T_AUTH_SYS.T_AUTH_SYS.CREATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return T_AUTH_SYS.T_AUTH_SYS.CREATE_USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field8() {
        return T_AUTH_SYS.T_AUTH_SYS.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return T_AUTH_SYS.T_AUTH_SYS.UPDATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return T_AUTH_SYS.T_AUTH_SYS.UPDATE_USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field11() {
        return T_AUTH_SYS.T_AUTH_SYS.DELETE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return T_AUTH_SYS.T_AUTH_SYS.DELETE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return T_AUTH_SYS.T_AUTH_SYS.DELETE_USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field14() {
        return T_AUTH_SYS.T_AUTH_SYS.ENABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSysName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSysDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getSysDomain();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component5() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getCreateUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component8() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getUpdateUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component11() {
        return getDeleteTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component12() {
        return getDeleteUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getDeleteUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component14() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSysName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSysDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSysDomain();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value5() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCreateUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value8() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getUpdateUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value11() {
        return getDeleteTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getDeleteUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getDeleteUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value14() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysRecord value1(UShort value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysRecord value2(String value) {
        setSysName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysRecord value3(String value) {
        setSysDesc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysRecord value4(String value) {
        setSysDomain(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysRecord value5(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysRecord value6(Integer value) {
        setCreateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysRecord value7(String value) {
        setCreateUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysRecord value8(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysRecord value9(Integer value) {
        setUpdateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysRecord value10(String value) {
        setUpdateUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysRecord value11(LocalDateTime value) {
        setDeleteTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysRecord value12(Integer value) {
        setDeleteUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysRecord value13(String value) {
        setDeleteUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysRecord value14(Boolean value) {
        setEnabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysRecord values(UShort value1, String value2, String value3, String value4, LocalDateTime value5, Integer value6, String value7, LocalDateTime value8, Integer value9, String value10, LocalDateTime value11, Integer value12, String value13, Boolean value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TAuthSysRecord
     */
    public TAuthSysRecord() {
        super(T_AUTH_SYS.T_AUTH_SYS);
    }

    /**
     * Create a detached, initialised TAuthSysRecord
     */
    public TAuthSysRecord(UShort id, String sysName, String sysDesc, String sysDomain, LocalDateTime createTime, Integer createUser, String createUserName, LocalDateTime updateTime, Integer updateUser, String updateUserName, LocalDateTime deleteTime, Integer deleteUser, String deleteUserName, Boolean enabled) {
        super(T_AUTH_SYS.T_AUTH_SYS);

        set(0, id);
        set(1, sysName);
        set(2, sysDesc);
        set(3, sysDomain);
        set(4, createTime);
        set(5, createUser);
        set(6, createUserName);
        set(7, updateTime);
        set(8, updateUser);
        set(9, updateUserName);
        set(10, deleteTime);
        set(11, deleteUser);
        set(12, deleteUserName);
        set(13, enabled);
    }
}
