/*
 * This file is generated by jOOQ.
*/
package com.luzhiqing.bamboo.entity.tables.records;


import com.luzhiqing.bamboo.entity.tables.TAuthSysMenu;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * 系统menu
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAuthSysMenuRecord extends UpdatableRecordImpl<TAuthSysMenuRecord> implements Record17<UInteger, UShort, UInteger, String, String, String, Byte, LocalDateTime, Integer, String, LocalDateTime, Integer, String, LocalDateTime, Integer, String, Boolean> {

    private static final long serialVersionUID = -304855179;

    /**
     * Setter for <code>bamboo_auth.t_auth_sys_menu.id</code>. 自增id
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_auth_sys_menu.id</code>. 自增id
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>bamboo_auth.t_auth_sys_menu.sys_id</code>. 系统id
     */
    public void setSysId(UShort value) {
        set(1, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_auth_sys_menu.sys_id</code>. 系统id
     */
    public UShort getSysId() {
        return (UShort) get(1);
    }

    /**
     * Setter for <code>bamboo_auth.t_auth_sys_menu.parent_id</code>. 父菜单id
     */
    public void setParentId(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_auth_sys_menu.parent_id</code>. 父菜单id
     */
    public UInteger getParentId() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>bamboo_auth.t_auth_sys_menu.menu_name</code>. 菜单名称
     */
    public void setMenuName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_auth_sys_menu.menu_name</code>. 菜单名称
     */
    public String getMenuName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bamboo_auth.t_auth_sys_menu.menu_desc</code>. 菜单描述
     */
    public void setMenuDesc(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_auth_sys_menu.menu_desc</code>. 菜单描述
     */
    public String getMenuDesc() {
        return (String) get(4);
    }

    /**
     * Setter for <code>bamboo_auth.t_auth_sys_menu.menu_uri</code>. 菜单uri
     */
    public void setMenuUri(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_auth_sys_menu.menu_uri</code>. 菜单uri
     */
    public String getMenuUri() {
        return (String) get(5);
    }

    /**
     * Setter for <code>bamboo_auth.t_auth_sys_menu.showing</code>. 是否展示菜单
     */
    public void setShowing(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_auth_sys_menu.showing</code>. 是否展示菜单
     */
    public Byte getShowing() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>bamboo_auth.t_auth_sys_menu.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_auth_sys_menu.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>bamboo_auth.t_auth_sys_menu.create_user</code>.
     */
    public void setCreateUser(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_auth_sys_menu.create_user</code>.
     */
    public Integer getCreateUser() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>bamboo_auth.t_auth_sys_menu.create_user_name</code>.
     */
    public void setCreateUserName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_auth_sys_menu.create_user_name</code>.
     */
    public String getCreateUserName() {
        return (String) get(9);
    }

    /**
     * Setter for <code>bamboo_auth.t_auth_sys_menu.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_auth_sys_menu.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>bamboo_auth.t_auth_sys_menu.update_user</code>.
     */
    public void setUpdateUser(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_auth_sys_menu.update_user</code>.
     */
    public Integer getUpdateUser() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>bamboo_auth.t_auth_sys_menu.update_user_name</code>.
     */
    public void setUpdateUserName(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_auth_sys_menu.update_user_name</code>.
     */
    public String getUpdateUserName() {
        return (String) get(12);
    }

    /**
     * Setter for <code>bamboo_auth.t_auth_sys_menu.delete_time</code>.
     */
    public void setDeleteTime(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_auth_sys_menu.delete_time</code>.
     */
    public LocalDateTime getDeleteTime() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>bamboo_auth.t_auth_sys_menu.delete_user</code>.
     */
    public void setDeleteUser(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_auth_sys_menu.delete_user</code>.
     */
    public Integer getDeleteUser() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>bamboo_auth.t_auth_sys_menu.delete_user_name</code>.
     */
    public void setDeleteUserName(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_auth_sys_menu.delete_user_name</code>.
     */
    public String getDeleteUserName() {
        return (String) get(15);
    }

    /**
     * Setter for <code>bamboo_auth.t_auth_sys_menu.enabled</code>.
     */
    public void setEnabled(Boolean value) {
        set(16, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_auth_sys_menu.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<UInteger, UShort, UInteger, String, String, String, Byte, LocalDateTime, Integer, String, LocalDateTime, Integer, String, LocalDateTime, Integer, String, Boolean> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<UInteger, UShort, UInteger, String, String, String, Byte, LocalDateTime, Integer, String, LocalDateTime, Integer, String, LocalDateTime, Integer, String, Boolean> valuesRow() {
        return (Row17) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return TAuthSysMenu.T_AUTH_SYS_MENU.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UShort> field2() {
        return TAuthSysMenu.T_AUTH_SYS_MENU.SYS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return TAuthSysMenu.T_AUTH_SYS_MENU.PARENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TAuthSysMenu.T_AUTH_SYS_MENU.MENU_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TAuthSysMenu.T_AUTH_SYS_MENU.MENU_DESC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TAuthSysMenu.T_AUTH_SYS_MENU.MENU_URI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field7() {
        return TAuthSysMenu.T_AUTH_SYS_MENU.SHOWING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field8() {
        return TAuthSysMenu.T_AUTH_SYS_MENU.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return TAuthSysMenu.T_AUTH_SYS_MENU.CREATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return TAuthSysMenu.T_AUTH_SYS_MENU.CREATE_USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field11() {
        return TAuthSysMenu.T_AUTH_SYS_MENU.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return TAuthSysMenu.T_AUTH_SYS_MENU.UPDATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return TAuthSysMenu.T_AUTH_SYS_MENU.UPDATE_USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field14() {
        return TAuthSysMenu.T_AUTH_SYS_MENU.DELETE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field15() {
        return TAuthSysMenu.T_AUTH_SYS_MENU.DELETE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return TAuthSysMenu.T_AUTH_SYS_MENU.DELETE_USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field17() {
        return TAuthSysMenu.T_AUTH_SYS_MENU.ENABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort component2() {
        return getSysId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component3() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getMenuName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getMenuDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getMenuUri();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component7() {
        return getShowing();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component8() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getCreateUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component11() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component12() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getUpdateUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component14() {
        return getDeleteTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component15() {
        return getDeleteUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component16() {
        return getDeleteUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component17() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UShort value2() {
        return getSysId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMenuName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMenuDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getMenuUri();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value7() {
        return getShowing();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value8() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getCreateUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value11() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getUpdateUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value14() {
        return getDeleteTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value15() {
        return getDeleteUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getDeleteUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value17() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysMenuRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysMenuRecord value2(UShort value) {
        setSysId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysMenuRecord value3(UInteger value) {
        setParentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysMenuRecord value4(String value) {
        setMenuName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysMenuRecord value5(String value) {
        setMenuDesc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysMenuRecord value6(String value) {
        setMenuUri(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysMenuRecord value7(Byte value) {
        setShowing(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysMenuRecord value8(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysMenuRecord value9(Integer value) {
        setCreateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysMenuRecord value10(String value) {
        setCreateUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysMenuRecord value11(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysMenuRecord value12(Integer value) {
        setUpdateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysMenuRecord value13(String value) {
        setUpdateUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysMenuRecord value14(LocalDateTime value) {
        setDeleteTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysMenuRecord value15(Integer value) {
        setDeleteUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysMenuRecord value16(String value) {
        setDeleteUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysMenuRecord value17(Boolean value) {
        setEnabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TAuthSysMenuRecord values(UInteger value1, UShort value2, UInteger value3, String value4, String value5, String value6, Byte value7, LocalDateTime value8, Integer value9, String value10, LocalDateTime value11, Integer value12, String value13, LocalDateTime value14, Integer value15, String value16, Boolean value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TAuthSysMenuRecord
     */
    public TAuthSysMenuRecord() {
        super(TAuthSysMenu.T_AUTH_SYS_MENU);
    }

    /**
     * Create a detached, initialised TAuthSysMenuRecord
     */
    public TAuthSysMenuRecord(UInteger id, UShort sysId, UInteger parentId, String menuName, String menuDesc, String menuUri, Byte showing, LocalDateTime createTime, Integer createUser, String createUserName, LocalDateTime updateTime, Integer updateUser, String updateUserName, LocalDateTime deleteTime, Integer deleteUser, String deleteUserName, Boolean enabled) {
        super(TAuthSysMenu.T_AUTH_SYS_MENU);

        set(0, id);
        set(1, sysId);
        set(2, parentId);
        set(3, menuName);
        set(4, menuDesc);
        set(5, menuUri);
        set(6, showing);
        set(7, createTime);
        set(8, createUser);
        set(9, createUserName);
        set(10, updateTime);
        set(11, updateUser);
        set(12, updateUserName);
        set(13, deleteTime);
        set(14, deleteUser);
        set(15, deleteUserName);
        set(16, enabled);
    }
}
