/*
 * This file is generated by jOOQ.
*/
package com.luzhiqing.bamboo.entity.tables.records;


import com.luzhiqing.bamboo.constants.enums.GenderType;
import com.luzhiqing.bamboo.entity.tables.TBambooUser;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * 账户信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TBambooUserRecord extends UpdatableRecordImpl<TBambooUserRecord> implements Record16<UInteger, UInteger, String, String, GenderType, UByte, LocalDateTime, Integer, String, LocalDateTime, Integer, String, LocalDateTime, Integer, String, Boolean> {

    private static final long serialVersionUID = -1022234713;

    /**
     * Setter for <code>bamboo_auth.t_bamboo_user.id</code>. 用户id
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_bamboo_user.id</code>. 用户id
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>bamboo_auth.t_bamboo_user.uid</code>. 账号id
     */
    public void setUid(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_bamboo_user.uid</code>. 账号id
     */
    public UInteger getUid() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>bamboo_auth.t_bamboo_user.nickname</code>. 昵称
     */
    public void setNickname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_bamboo_user.nickname</code>. 昵称
     */
    public String getNickname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bamboo_auth.t_bamboo_user.avatar</code>. 头像(相对路径)
     */
    public void setAvatar(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_bamboo_user.avatar</code>. 头像(相对路径)
     */
    public String getAvatar() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bamboo_auth.t_bamboo_user.gender</code>. 性别
     */
    public void setGender(GenderType value) {
        set(4, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_bamboo_user.gender</code>. 性别
     */
    public GenderType getGender() {
        return (GenderType) get(4);
    }

    /**
     * Setter for <code>bamboo_auth.t_bamboo_user.user_role</code>. 角色 0:普通用户 1:vip
     */
    public void setUserRole(UByte value) {
        set(5, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_bamboo_user.user_role</code>. 角色 0:普通用户 1:vip
     */
    public UByte getUserRole() {
        return (UByte) get(5);
    }

    /**
     * Setter for <code>bamboo_auth.t_bamboo_user.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_bamboo_user.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>bamboo_auth.t_bamboo_user.create_user</code>.
     */
    public void setCreateUser(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_bamboo_user.create_user</code>.
     */
    public Integer getCreateUser() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>bamboo_auth.t_bamboo_user.create_user_name</code>.
     */
    public void setCreateUserName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_bamboo_user.create_user_name</code>.
     */
    public String getCreateUserName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>bamboo_auth.t_bamboo_user.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_bamboo_user.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>bamboo_auth.t_bamboo_user.update_user</code>.
     */
    public void setUpdateUser(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_bamboo_user.update_user</code>.
     */
    public Integer getUpdateUser() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>bamboo_auth.t_bamboo_user.update_user_name</code>.
     */
    public void setUpdateUserName(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_bamboo_user.update_user_name</code>.
     */
    public String getUpdateUserName() {
        return (String) get(11);
    }

    /**
     * Setter for <code>bamboo_auth.t_bamboo_user.delete_time</code>.
     */
    public void setDeleteTime(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_bamboo_user.delete_time</code>.
     */
    public LocalDateTime getDeleteTime() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>bamboo_auth.t_bamboo_user.delete_user</code>.
     */
    public void setDeleteUser(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_bamboo_user.delete_user</code>.
     */
    public Integer getDeleteUser() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>bamboo_auth.t_bamboo_user.delete_user_name</code>.
     */
    public void setDeleteUserName(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_bamboo_user.delete_user_name</code>.
     */
    public String getDeleteUserName() {
        return (String) get(14);
    }

    /**
     * Setter for <code>bamboo_auth.t_bamboo_user.enabled</code>.
     */
    public void setEnabled(Boolean value) {
        set(15, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_bamboo_user.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<UInteger, UInteger, String, String, GenderType, UByte, LocalDateTime, Integer, String, LocalDateTime, Integer, String, LocalDateTime, Integer, String, Boolean> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<UInteger, UInteger, String, String, GenderType, UByte, LocalDateTime, Integer, String, LocalDateTime, Integer, String, LocalDateTime, Integer, String, Boolean> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return TBambooUser.T_BAMBOO_USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return TBambooUser.T_BAMBOO_USER.UID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TBambooUser.T_BAMBOO_USER.NICKNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TBambooUser.T_BAMBOO_USER.AVATAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<GenderType> field5() {
        return TBambooUser.T_BAMBOO_USER.GENDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field6() {
        return TBambooUser.T_BAMBOO_USER.USER_ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field7() {
        return TBambooUser.T_BAMBOO_USER.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return TBambooUser.T_BAMBOO_USER.CREATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return TBambooUser.T_BAMBOO_USER.CREATE_USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field10() {
        return TBambooUser.T_BAMBOO_USER.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return TBambooUser.T_BAMBOO_USER.UPDATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return TBambooUser.T_BAMBOO_USER.UPDATE_USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field13() {
        return TBambooUser.T_BAMBOO_USER.DELETE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return TBambooUser.T_BAMBOO_USER.DELETE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return TBambooUser.T_BAMBOO_USER.DELETE_USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field16() {
        return TBambooUser.T_BAMBOO_USER.ENABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getNickname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GenderType component5() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component6() {
        return getUserRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getCreateUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component10() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getUpdateUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component13() {
        return getDeleteTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component14() {
        return getDeleteUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getDeleteUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component16() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getNickname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GenderType value5() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value6() {
        return getUserRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCreateUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value10() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getUpdateUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value13() {
        return getDeleteTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getDeleteUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getDeleteUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value16() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBambooUserRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBambooUserRecord value2(UInteger value) {
        setUid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBambooUserRecord value3(String value) {
        setNickname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBambooUserRecord value4(String value) {
        setAvatar(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBambooUserRecord value5(GenderType value) {
        setGender(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBambooUserRecord value6(UByte value) {
        setUserRole(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBambooUserRecord value7(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBambooUserRecord value8(Integer value) {
        setCreateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBambooUserRecord value9(String value) {
        setCreateUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBambooUserRecord value10(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBambooUserRecord value11(Integer value) {
        setUpdateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBambooUserRecord value12(String value) {
        setUpdateUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBambooUserRecord value13(LocalDateTime value) {
        setDeleteTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBambooUserRecord value14(Integer value) {
        setDeleteUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBambooUserRecord value15(String value) {
        setDeleteUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBambooUserRecord value16(Boolean value) {
        setEnabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBambooUserRecord values(UInteger value1, UInteger value2, String value3, String value4, GenderType value5, UByte value6, LocalDateTime value7, Integer value8, String value9, LocalDateTime value10, Integer value11, String value12, LocalDateTime value13, Integer value14, String value15, Boolean value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TBambooUserRecord
     */
    public TBambooUserRecord() {
        super(TBambooUser.T_BAMBOO_USER);
    }

    /**
     * Create a detached, initialised TBambooUserRecord
     */
    public TBambooUserRecord(UInteger id, UInteger uid, String nickname, String avatar, GenderType gender, UByte userRole, LocalDateTime createTime, Integer createUser, String createUserName, LocalDateTime updateTime, Integer updateUser, String updateUserName, LocalDateTime deleteTime, Integer deleteUser, String deleteUserName, Boolean enabled) {
        super(TBambooUser.T_BAMBOO_USER);

        set(0, id);
        set(1, uid);
        set(2, nickname);
        set(3, avatar);
        set(4, gender);
        set(5, userRole);
        set(6, createTime);
        set(7, createUser);
        set(8, createUserName);
        set(9, updateTime);
        set(10, updateUser);
        set(11, updateUserName);
        set(12, deleteTime);
        set(13, deleteUser);
        set(14, deleteUserName);
        set(15, enabled);
    }
}
