/*
 * This file is generated by jOOQ.
*/
package com.luzhiqing.bamboo.entity.tables.records;


import com.luzhiqing.bamboo.constants.enums.GenderType;
import com.luzhiqing.bamboo.entity.tables.TStaff;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * 员工信息(这里列了大概的信息，多的可以垂直拆表)
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TStaffRecord extends UpdatableRecordImpl<TStaffRecord> implements Record18<UInteger, UInteger, String, String, String, String, String, GenderType, LocalDateTime, Integer, String, LocalDateTime, Integer, String, LocalDateTime, Integer, String, Boolean> {

    private static final long serialVersionUID = 155536236;

    /**
     * Setter for <code>bamboo_auth.t_staff.id</code>. 员工id
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_staff.id</code>. 员工id
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>bamboo_auth.t_staff.uid</code>. 账号id
     */
    public void setUid(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_staff.uid</code>. 账号id
     */
    public UInteger getUid() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>bamboo_auth.t_staff.email</code>. 员工邮箱
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_staff.email</code>. 员工邮箱
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bamboo_auth.t_staff.phone</code>. 员工手机号
     */
    public void setPhone(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_staff.phone</code>. 员工手机号
     */
    public String getPhone() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bamboo_auth.t_staff.staff_name</code>. 员工姓名
     */
    public void setStaffName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_staff.staff_name</code>. 员工姓名
     */
    public String getStaffName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>bamboo_auth.t_staff.nickname</code>. 员工昵称
     */
    public void setNickname(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_staff.nickname</code>. 员工昵称
     */
    public String getNickname() {
        return (String) get(5);
    }

    /**
     * Setter for <code>bamboo_auth.t_staff.avatar</code>. 员工头像(相对路径)
     */
    public void setAvatar(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_staff.avatar</code>. 员工头像(相对路径)
     */
    public String getAvatar() {
        return (String) get(6);
    }

    /**
     * Setter for <code>bamboo_auth.t_staff.gender</code>. 员工性别
     */
    public void setGender(GenderType value) {
        set(7, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_staff.gender</code>. 员工性别
     */
    public GenderType getGender() {
        return (GenderType) get(7);
    }

    /**
     * Setter for <code>bamboo_auth.t_staff.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_staff.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>bamboo_auth.t_staff.create_user</code>.
     */
    public void setCreateUser(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_staff.create_user</code>.
     */
    public Integer getCreateUser() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>bamboo_auth.t_staff.create_user_name</code>.
     */
    public void setCreateUserName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_staff.create_user_name</code>.
     */
    public String getCreateUserName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>bamboo_auth.t_staff.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_staff.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>bamboo_auth.t_staff.update_user</code>.
     */
    public void setUpdateUser(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_staff.update_user</code>.
     */
    public Integer getUpdateUser() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>bamboo_auth.t_staff.update_user_name</code>.
     */
    public void setUpdateUserName(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_staff.update_user_name</code>.
     */
    public String getUpdateUserName() {
        return (String) get(13);
    }

    /**
     * Setter for <code>bamboo_auth.t_staff.delete_time</code>.
     */
    public void setDeleteTime(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_staff.delete_time</code>.
     */
    public LocalDateTime getDeleteTime() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>bamboo_auth.t_staff.delete_user</code>.
     */
    public void setDeleteUser(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_staff.delete_user</code>.
     */
    public Integer getDeleteUser() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>bamboo_auth.t_staff.delete_user_name</code>.
     */
    public void setDeleteUserName(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_staff.delete_user_name</code>.
     */
    public String getDeleteUserName() {
        return (String) get(16);
    }

    /**
     * Setter for <code>bamboo_auth.t_staff.enabled</code>.
     */
    public void setEnabled(Boolean value) {
        set(17, value);
    }

    /**
     * Getter for <code>bamboo_auth.t_staff.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<UInteger, UInteger, String, String, String, String, String, GenderType, LocalDateTime, Integer, String, LocalDateTime, Integer, String, LocalDateTime, Integer, String, Boolean> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<UInteger, UInteger, String, String, String, String, String, GenderType, LocalDateTime, Integer, String, LocalDateTime, Integer, String, LocalDateTime, Integer, String, Boolean> valuesRow() {
        return (Row18) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return TStaff.T_STAFF.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return TStaff.T_STAFF.UID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TStaff.T_STAFF.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TStaff.T_STAFF.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TStaff.T_STAFF.STAFF_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TStaff.T_STAFF.NICKNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TStaff.T_STAFF.AVATAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<GenderType> field8() {
        return TStaff.T_STAFF.GENDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field9() {
        return TStaff.T_STAFF.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return TStaff.T_STAFF.CREATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return TStaff.T_STAFF.CREATE_USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field12() {
        return TStaff.T_STAFF.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return TStaff.T_STAFF.UPDATE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return TStaff.T_STAFF.UPDATE_USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field15() {
        return TStaff.T_STAFF.DELETE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field16() {
        return TStaff.T_STAFF.DELETE_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return TStaff.T_STAFF.DELETE_USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field18() {
        return TStaff.T_STAFF.ENABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getStaffName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getNickname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GenderType component8() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component9() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getCreateUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component12() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component13() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getUpdateUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component15() {
        return getDeleteTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component16() {
        return getDeleteUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component17() {
        return getDeleteUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component18() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getStaffName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getNickname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GenderType value8() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value9() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getCreateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getCreateUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value12() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getUpdateUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getUpdateUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value15() {
        return getDeleteTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value16() {
        return getDeleteUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getDeleteUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value18() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TStaffRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TStaffRecord value2(UInteger value) {
        setUid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TStaffRecord value3(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TStaffRecord value4(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TStaffRecord value5(String value) {
        setStaffName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TStaffRecord value6(String value) {
        setNickname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TStaffRecord value7(String value) {
        setAvatar(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TStaffRecord value8(GenderType value) {
        setGender(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TStaffRecord value9(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TStaffRecord value10(Integer value) {
        setCreateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TStaffRecord value11(String value) {
        setCreateUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TStaffRecord value12(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TStaffRecord value13(Integer value) {
        setUpdateUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TStaffRecord value14(String value) {
        setUpdateUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TStaffRecord value15(LocalDateTime value) {
        setDeleteTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TStaffRecord value16(Integer value) {
        setDeleteUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TStaffRecord value17(String value) {
        setDeleteUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TStaffRecord value18(Boolean value) {
        setEnabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TStaffRecord values(UInteger value1, UInteger value2, String value3, String value4, String value5, String value6, String value7, GenderType value8, LocalDateTime value9, Integer value10, String value11, LocalDateTime value12, Integer value13, String value14, LocalDateTime value15, Integer value16, String value17, Boolean value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TStaffRecord
     */
    public TStaffRecord() {
        super(TStaff.T_STAFF);
    }

    /**
     * Create a detached, initialised TStaffRecord
     */
    public TStaffRecord(UInteger id, UInteger uid, String email, String phone, String staffName, String nickname, String avatar, GenderType gender, LocalDateTime createTime, Integer createUser, String createUserName, LocalDateTime updateTime, Integer updateUser, String updateUserName, LocalDateTime deleteTime, Integer deleteUser, String deleteUserName, Boolean enabled) {
        super(TStaff.T_STAFF);

        set(0, id);
        set(1, uid);
        set(2, email);
        set(3, phone);
        set(4, staffName);
        set(5, nickname);
        set(6, avatar);
        set(7, gender);
        set(8, createTime);
        set(9, createUser);
        set(10, createUserName);
        set(11, updateTime);
        set(12, updateUser);
        set(13, updateUserName);
        set(14, deleteTime);
        set(15, deleteUser);
        set(16, deleteUserName);
        set(17, enabled);
    }
}
