/*
 * This file is generated by jOOQ.
*/
package com.luzhiqing.bamboo.entity.tables.pojos;


import com.luzhiqing.bamboo.constants.enums.AccountType;
import org.jooq.types.UInteger;

import javax.annotation.Generated;
import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 第三方用户信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAccountPlatform implements Serializable {

    private static final long serialVersionUID = -396460812;

    private UInteger      id;
    private UInteger      uid;
    private String        platformId;
    private String        platformToken;
    private String        sessionKey;
    private AccountType   accountType;
    private String        nickname;
    private String        avatar;
    private LocalDateTime createTime;
    private Integer       createUser;
    private String        createUserName;
    private LocalDateTime updateTime;
    private Integer       updateUser;
    private String        updateUserName;
    private LocalDateTime deleteTime;
    private Integer       deleteUser;
    private String        deleteUserName;
    private Boolean       enabled;

    public TAccountPlatform() {}

    public TAccountPlatform(TAccountPlatform value) {
        this.id = value.id;
        this.uid = value.uid;
        this.platformId = value.platformId;
        this.platformToken = value.platformToken;
        this.accountType = value.accountType;
        this.nickname = value.nickname;
        this.avatar = value.avatar;
        this.createTime = value.createTime;
        this.createUser = value.createUser;
        this.createUserName = value.createUserName;
        this.updateTime = value.updateTime;
        this.updateUser = value.updateUser;
        this.updateUserName = value.updateUserName;
        this.deleteTime = value.deleteTime;
        this.deleteUser = value.deleteUser;
        this.deleteUserName = value.deleteUserName;
        this.enabled = value.enabled;
    }

    public TAccountPlatform(
        UInteger      id,
        UInteger      uid,
        String        platformId,
        String        platformToken,
        AccountType   accountType,
        String        nickname,
        String        avatar,
        LocalDateTime createTime,
        Integer       createUser,
        String        createUserName,
        LocalDateTime updateTime,
        Integer       updateUser,
        String        updateUserName,
        LocalDateTime deleteTime,
        Integer       deleteUser,
        String        deleteUserName,
        Boolean       enabled
    ) {
        this.id = id;
        this.uid = uid;
        this.platformId = platformId;
        this.platformToken = platformToken;
        this.accountType = accountType;
        this.nickname = nickname;
        this.avatar = avatar;
        this.createTime = createTime;
        this.createUser = createUser;
        this.createUserName = createUserName;
        this.updateTime = updateTime;
        this.updateUser = updateUser;
        this.updateUserName = updateUserName;
        this.deleteTime = deleteTime;
        this.deleteUser = deleteUser;
        this.deleteUserName = deleteUserName;
        this.enabled = enabled;
    }

    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    public UInteger getUid() {
        return this.uid;
    }

    public void setUid(UInteger uid) {
        this.uid = uid;
    }

    public String getPlatformId() {
        return this.platformId;
    }

    public void setPlatformId(String platformId) {
        this.platformId = platformId;
    }

    public String getPlatformToken() {
        return this.platformToken;
    }

    public void setPlatformToken(String platformToken) {
        this.platformToken = platformToken;
    }

    public AccountType getAccountType() {
        return this.accountType;
    }

    public void setAccountType(AccountType accountType) {
        this.accountType = accountType;
    }

    public String getNickname() {
        return this.nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getAvatar() {
        return this.avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public Integer getCreateUser() {
        return this.createUser;
    }

    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    public String getCreateUserName() {
        return this.createUserName;
    }

    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName;
    }

    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getUpdateUser() {
        return this.updateUser;
    }

    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    public String getUpdateUserName() {
        return this.updateUserName;
    }

    public void setUpdateUserName(String updateUserName) {
        this.updateUserName = updateUserName;
    }

    public LocalDateTime getDeleteTime() {
        return this.deleteTime;
    }

    public void setDeleteTime(LocalDateTime deleteTime) {
        this.deleteTime = deleteTime;
    }

    public Integer getDeleteUser() {
        return this.deleteUser;
    }

    public void setDeleteUser(Integer deleteUser) {
        this.deleteUser = deleteUser;
    }

    public String getDeleteUserName() {
        return this.deleteUserName;
    }

    public void setDeleteUserName(String deleteUserName) {
        this.deleteUserName = deleteUserName;
    }

    public Boolean getEnabled() {
        return this.enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    public String getSessionKey() {
        return sessionKey;
    }

    public void setSessionKey(String sessionKey) {
        this.sessionKey = sessionKey;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TAccountPlatform (");

        sb.append(id);
        sb.append(", ").append(uid);
        sb.append(", ").append(platformId);
        sb.append(", ").append(platformToken);
        sb.append(", ").append(accountType);
        sb.append(", ").append(nickname);
        sb.append(", ").append(avatar);
        sb.append(", ").append(createTime);
        sb.append(", ").append(createUser);
        sb.append(", ").append(createUserName);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(updateUser);
        sb.append(", ").append(updateUserName);
        sb.append(", ").append(deleteTime);
        sb.append(", ").append(deleteUser);
        sb.append(", ").append(deleteUserName);
        sb.append(", ").append(enabled);

        sb.append(")");
        return sb.toString();
    }
}
