/*
 * This file is generated by jOOQ.
*/
package com.luzhiqing.bamboo.entity.tables.pojos;


import org.jooq.types.UShort;

import javax.annotation.Generated;
import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 系统map(登记目前存在的后台系统信息)
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAuthSys implements Serializable {

    private static final long serialVersionUID = -1479409529;

    private UShort        id;
    private String        sysName;
    private String        sysDesc;
    private String        sysDomain;
    private LocalDateTime createTime;
    private Integer       createUser;
    private String        createUserName;
    private LocalDateTime updateTime;
    private Integer       updateUser;
    private String        updateUserName;
    private LocalDateTime deleteTime;
    private Integer       deleteUser;
    private String        deleteUserName;
    private Boolean       enabled;

    public TAuthSys() {}

    public TAuthSys(TAuthSys value) {
        this.id = value.id;
        this.sysName = value.sysName;
        this.sysDesc = value.sysDesc;
        this.sysDomain = value.sysDomain;
        this.createTime = value.createTime;
        this.createUser = value.createUser;
        this.createUserName = value.createUserName;
        this.updateTime = value.updateTime;
        this.updateUser = value.updateUser;
        this.updateUserName = value.updateUserName;
        this.deleteTime = value.deleteTime;
        this.deleteUser = value.deleteUser;
        this.deleteUserName = value.deleteUserName;
        this.enabled = value.enabled;
    }

    public TAuthSys(
        UShort        id,
        String        sysName,
        String        sysDesc,
        String        sysDomain,
        LocalDateTime createTime,
        Integer       createUser,
        String        createUserName,
        LocalDateTime updateTime,
        Integer       updateUser,
        String        updateUserName,
        LocalDateTime deleteTime,
        Integer       deleteUser,
        String        deleteUserName,
        Boolean       enabled
    ) {
        this.id = id;
        this.sysName = sysName;
        this.sysDesc = sysDesc;
        this.sysDomain = sysDomain;
        this.createTime = createTime;
        this.createUser = createUser;
        this.createUserName = createUserName;
        this.updateTime = updateTime;
        this.updateUser = updateUser;
        this.updateUserName = updateUserName;
        this.deleteTime = deleteTime;
        this.deleteUser = deleteUser;
        this.deleteUserName = deleteUserName;
        this.enabled = enabled;
    }

    public UShort getId() {
        return this.id;
    }

    public void setId(UShort id) {
        this.id = id;
    }

    public String getSysName() {
        return this.sysName;
    }

    public void setSysName(String sysName) {
        this.sysName = sysName;
    }

    public String getSysDesc() {
        return this.sysDesc;
    }

    public void setSysDesc(String sysDesc) {
        this.sysDesc = sysDesc;
    }

    public String getSysDomain() {
        return this.sysDomain;
    }

    public void setSysDomain(String sysDomain) {
        this.sysDomain = sysDomain;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public Integer getCreateUser() {
        return this.createUser;
    }

    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    public String getCreateUserName() {
        return this.createUserName;
    }

    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName;
    }

    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getUpdateUser() {
        return this.updateUser;
    }

    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    public String getUpdateUserName() {
        return this.updateUserName;
    }

    public void setUpdateUserName(String updateUserName) {
        this.updateUserName = updateUserName;
    }

    public LocalDateTime getDeleteTime() {
        return this.deleteTime;
    }

    public void setDeleteTime(LocalDateTime deleteTime) {
        this.deleteTime = deleteTime;
    }

    public Integer getDeleteUser() {
        return this.deleteUser;
    }

    public void setDeleteUser(Integer deleteUser) {
        this.deleteUser = deleteUser;
    }

    public String getDeleteUserName() {
        return this.deleteUserName;
    }

    public void setDeleteUserName(String deleteUserName) {
        this.deleteUserName = deleteUserName;
    }

    public Boolean getEnabled() {
        return this.enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TAuthSys (");

        sb.append(id);
        sb.append(", ").append(sysName);
        sb.append(", ").append(sysDesc);
        sb.append(", ").append(sysDomain);
        sb.append(", ").append(createTime);
        sb.append(", ").append(createUser);
        sb.append(", ").append(createUserName);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(updateUser);
        sb.append(", ").append(updateUserName);
        sb.append(", ").append(deleteTime);
        sb.append(", ").append(deleteUser);
        sb.append(", ").append(deleteUserName);
        sb.append(", ").append(enabled);

        sb.append(")");
        return sb.toString();
    }
}
