/*
 * This file is generated by jOOQ.
*/
package com.luzhiqing.bamboo.entity.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * 系统menu
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TAuthSysMenu implements Serializable {

    private static final long serialVersionUID = 1395566068;

    private UInteger      id;
    private UShort        sysId;
    private UInteger      parentId;
    private String        menuName;
    private String        menuDesc;
    private String        menuUri;
    private Byte          showing;
    private LocalDateTime createTime;
    private Integer       createUser;
    private String        createUserName;
    private LocalDateTime updateTime;
    private Integer       updateUser;
    private String        updateUserName;
    private LocalDateTime deleteTime;
    private Integer       deleteUser;
    private String        deleteUserName;
    private Boolean       enabled;

    public TAuthSysMenu() {}

    public TAuthSysMenu(TAuthSysMenu value) {
        this.id = value.id;
        this.sysId = value.sysId;
        this.parentId = value.parentId;
        this.menuName = value.menuName;
        this.menuDesc = value.menuDesc;
        this.menuUri = value.menuUri;
        this.showing = value.showing;
        this.createTime = value.createTime;
        this.createUser = value.createUser;
        this.createUserName = value.createUserName;
        this.updateTime = value.updateTime;
        this.updateUser = value.updateUser;
        this.updateUserName = value.updateUserName;
        this.deleteTime = value.deleteTime;
        this.deleteUser = value.deleteUser;
        this.deleteUserName = value.deleteUserName;
        this.enabled = value.enabled;
    }

    public TAuthSysMenu(
        UInteger      id,
        UShort        sysId,
        UInteger      parentId,
        String        menuName,
        String        menuDesc,
        String        menuUri,
        Byte          showing,
        LocalDateTime createTime,
        Integer       createUser,
        String        createUserName,
        LocalDateTime updateTime,
        Integer       updateUser,
        String        updateUserName,
        LocalDateTime deleteTime,
        Integer       deleteUser,
        String        deleteUserName,
        Boolean       enabled
    ) {
        this.id = id;
        this.sysId = sysId;
        this.parentId = parentId;
        this.menuName = menuName;
        this.menuDesc = menuDesc;
        this.menuUri = menuUri;
        this.showing = showing;
        this.createTime = createTime;
        this.createUser = createUser;
        this.createUserName = createUserName;
        this.updateTime = updateTime;
        this.updateUser = updateUser;
        this.updateUserName = updateUserName;
        this.deleteTime = deleteTime;
        this.deleteUser = deleteUser;
        this.deleteUserName = deleteUserName;
        this.enabled = enabled;
    }

    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    public UShort getSysId() {
        return this.sysId;
    }

    public void setSysId(UShort sysId) {
        this.sysId = sysId;
    }

    public UInteger getParentId() {
        return this.parentId;
    }

    public void setParentId(UInteger parentId) {
        this.parentId = parentId;
    }

    public String getMenuName() {
        return this.menuName;
    }

    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    public String getMenuDesc() {
        return this.menuDesc;
    }

    public void setMenuDesc(String menuDesc) {
        this.menuDesc = menuDesc;
    }

    public String getMenuUri() {
        return this.menuUri;
    }

    public void setMenuUri(String menuUri) {
        this.menuUri = menuUri;
    }

    public Byte getShowing() {
        return this.showing;
    }

    public void setShowing(Byte showing) {
        this.showing = showing;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public Integer getCreateUser() {
        return this.createUser;
    }

    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    public String getCreateUserName() {
        return this.createUserName;
    }

    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName;
    }

    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getUpdateUser() {
        return this.updateUser;
    }

    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    public String getUpdateUserName() {
        return this.updateUserName;
    }

    public void setUpdateUserName(String updateUserName) {
        this.updateUserName = updateUserName;
    }

    public LocalDateTime getDeleteTime() {
        return this.deleteTime;
    }

    public void setDeleteTime(LocalDateTime deleteTime) {
        this.deleteTime = deleteTime;
    }

    public Integer getDeleteUser() {
        return this.deleteUser;
    }

    public void setDeleteUser(Integer deleteUser) {
        this.deleteUser = deleteUser;
    }

    public String getDeleteUserName() {
        return this.deleteUserName;
    }

    public void setDeleteUserName(String deleteUserName) {
        this.deleteUserName = deleteUserName;
    }

    public Boolean getEnabled() {
        return this.enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TAuthSysMenu (");

        sb.append(id);
        sb.append(", ").append(sysId);
        sb.append(", ").append(parentId);
        sb.append(", ").append(menuName);
        sb.append(", ").append(menuDesc);
        sb.append(", ").append(menuUri);
        sb.append(", ").append(showing);
        sb.append(", ").append(createTime);
        sb.append(", ").append(createUser);
        sb.append(", ").append(createUserName);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(updateUser);
        sb.append(", ").append(updateUserName);
        sb.append(", ").append(deleteTime);
        sb.append(", ").append(deleteUser);
        sb.append(", ").append(deleteUserName);
        sb.append(", ").append(enabled);

        sb.append(")");
        return sb.toString();
    }
}
