/*
 * This file is generated by jOOQ.
*/
package com.luzhiqing.bamboo.entity;


import com.luzhiqing.bamboo.entity.tables.TAccountPlatform;
import com.luzhiqing.bamboo.entity.tables.TAccountUser;
import com.luzhiqing.bamboo.entity.tables.TAuthItem;
import com.luzhiqing.bamboo.entity.tables.TAuthRole;
import com.luzhiqing.bamboo.entity.tables.TAuthRoleStaffMapping;
import com.luzhiqing.bamboo.entity.tables.TAuthSys;
import com.luzhiqing.bamboo.entity.tables.TAuthSysMenu;
import com.luzhiqing.bamboo.entity.tables.TBambooUser;
import com.luzhiqing.bamboo.entity.tables.TStaff;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BambooAuth extends SchemaImpl {

    private static final long serialVersionUID = -1451227089;

    /**
     * The reference instance of <code>bamboo_auth</code>
     */
    public static final BambooAuth BAMBOO_AUTH = new BambooAuth();

    /**
     * 第三方用户信息
     */
    public final TAccountPlatform T_ACCOUNT_PLATFORM = TAccountPlatform.T_ACCOUNT_PLATFORM;

    /**
     * 账户
     */
    public final TAccountUser T_ACCOUNT_USER = TAccountUser.T_ACCOUNT_USER;

    /**
     * 系统权限
     */
    public final TAuthItem T_AUTH_ITEM = TAuthItem.T_AUTH_ITEM;

    /**
     * 员工角色
     */
    public final TAuthRole T_AUTH_ROLE = TAuthRole.T_AUTH_ROLE;

    /**
     * 权限角色与员工关系
     */
    public final TAuthRoleStaffMapping T_AUTH_ROLE_STAFF_MAPPING = TAuthRoleStaffMapping.T_AUTH_ROLE_STAFF_MAPPING;

    /**
     * 系统map(登记目前存在的后台系统信息)
     */
    public final TAuthSys T_AUTH_SYS = TAuthSys.T_AUTH_SYS;

    /**
     * 系统menu
     */
    public final TAuthSysMenu T_AUTH_SYS_MENU = TAuthSysMenu.T_AUTH_SYS_MENU;

    /**
     * 账户信息
     */
    public final TBambooUser T_BAMBOO_USER = TBambooUser.T_BAMBOO_USER;

    /**
     * 员工信息(这里列了大概的信息，多的可以垂直拆表)
     */
    public final TStaff T_STAFF = TStaff.T_STAFF;

    /**
     * No further instances allowed
     */
    private BambooAuth() {
        super("bamboo_auth", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TAccountPlatform.T_ACCOUNT_PLATFORM,
            TAccountUser.T_ACCOUNT_USER,
            TAuthItem.T_AUTH_ITEM,
            TAuthRole.T_AUTH_ROLE,
            TAuthRoleStaffMapping.T_AUTH_ROLE_STAFF_MAPPING,
            TAuthSys.T_AUTH_SYS,
            TAuthSysMenu.T_AUTH_SYS_MENU,
            TBambooUser.T_BAMBOO_USER,
            TStaff.T_STAFF);
    }
}
