/*
 * This file is generated by jOOQ.
*/
package com.luzhiqing.bamboo.entity;


import com.luzhiqing.bamboo.entity.tables.*;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BambooAuth extends SchemaImpl {

    private static final long serialVersionUID = 492361951;

    /**
     * The reference instance of <code>bamboo_auth</code>
     */
    public static final BambooAuth BAMBOO_AUTH = new BambooAuth();

    /**
     * 第三方用户信息
     */
    public final T_ACCOUNT_PLATFORM T_ACCOUNT_PLATFORM = com.luzhiqing.bamboo.entity.tables.T_ACCOUNT_PLATFORM.T_ACCOUNT_PLATFORM;

    /**
     * 账户
     */
    public final T_ACCOUNT_USER T_ACCOUNT_USER = com.luzhiqing.bamboo.entity.tables.T_ACCOUNT_USER.T_ACCOUNT_USER;

    /**
     * 系统权限
     */
    public final T_AUTH_ITEM T_AUTH_ITEM = com.luzhiqing.bamboo.entity.tables.T_AUTH_ITEM.T_AUTH_ITEM;

    /**
     * 员工角色
     */
    public final T_AUTH_ROLE T_AUTH_ROLE = com.luzhiqing.bamboo.entity.tables.T_AUTH_ROLE.T_AUTH_ROLE;

    /**
     * 权限角色与员工关系
     */
    public final T_AUTH_ROLE_STAFF_MAPPING T_AUTH_ROLE_STAFF_MAPPING = com.luzhiqing.bamboo.entity.tables.T_AUTH_ROLE_STAFF_MAPPING.T_AUTH_ROLE_STAFF_MAPPING;

    /**
     * 系统map(登记目前存在的后台系统信息)
     */
    public final T_AUTH_SYS T_AUTH_SYS = com.luzhiqing.bamboo.entity.tables.T_AUTH_SYS.T_AUTH_SYS;

    /**
     * 系统menu
     */
    public final T_AUTH_SYS_MENU T_AUTH_SYS_MENU = com.luzhiqing.bamboo.entity.tables.T_AUTH_SYS_MENU.T_AUTH_SYS_MENU;

    /**
     * 账户信息
     */
    public final T_BAMBOO_USER T_BAMBOO_USER = com.luzhiqing.bamboo.entity.tables.T_BAMBOO_USER.T_BAMBOO_USER;

    /**
     * 员工信息(这里列了大概的信息，多的可以垂直拆表)
     */
    public final T_STAFF T_STAFF = com.luzhiqing.bamboo.entity.tables.T_STAFF.T_STAFF;

    /**
     * No further instances allowed
     */
    private BambooAuth() {
        super("bamboo_auth", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            T_ACCOUNT_PLATFORM.T_ACCOUNT_PLATFORM,
            T_ACCOUNT_USER.T_ACCOUNT_USER,
            T_AUTH_ITEM.T_AUTH_ITEM,
            T_AUTH_ROLE.T_AUTH_ROLE,
            T_AUTH_ROLE_STAFF_MAPPING.T_AUTH_ROLE_STAFF_MAPPING,
            T_AUTH_SYS.T_AUTH_SYS,
            T_AUTH_SYS_MENU.T_AUTH_SYS_MENU,
            T_BAMBOO_USER.T_BAMBOO_USER,
            T_STAFF.T_STAFF);
    }
}
