/*
 * This file is generated by jOOQ.
*/
package com.luzhiqing.bamboo.entity;


import com.luzhiqing.bamboo.entity.tables.TAccountPlatform;
import com.luzhiqing.bamboo.entity.tables.TAccountUser;
import com.luzhiqing.bamboo.entity.tables.TAuthItem;
import com.luzhiqing.bamboo.entity.tables.TAuthRole;
import com.luzhiqing.bamboo.entity.tables.TAuthRoleStaffMapping;
import com.luzhiqing.bamboo.entity.tables.TAuthSys;
import com.luzhiqing.bamboo.entity.tables.TAuthSysMenu;
import com.luzhiqing.bamboo.entity.tables.TBambooUser;
import com.luzhiqing.bamboo.entity.tables.TStaff;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>bamboo_auth</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index T_ACCOUNT_PLATFORM_IDX_PLATFORM_ID = Indexes0.T_ACCOUNT_PLATFORM_IDX_PLATFORM_ID;
    public static final Index T_ACCOUNT_PLATFORM_IDX_UID = Indexes0.T_ACCOUNT_PLATFORM_IDX_UID;
    public static final Index T_ACCOUNT_PLATFORM_PRIMARY = Indexes0.T_ACCOUNT_PLATFORM_PRIMARY;
    public static final Index T_ACCOUNT_USER_IDX_EMAIL = Indexes0.T_ACCOUNT_USER_IDX_EMAIL;
    public static final Index T_ACCOUNT_USER_IDX_PHONE = Indexes0.T_ACCOUNT_USER_IDX_PHONE;
    public static final Index T_ACCOUNT_USER_IDX_USER_NAME = Indexes0.T_ACCOUNT_USER_IDX_USER_NAME;
    public static final Index T_ACCOUNT_USER_PRIMARY = Indexes0.T_ACCOUNT_USER_PRIMARY;
    public static final Index T_AUTH_ITEM_IDX_SYS_MENU = Indexes0.T_AUTH_ITEM_IDX_SYS_MENU;
    public static final Index T_AUTH_ITEM_PRIMARY = Indexes0.T_AUTH_ITEM_PRIMARY;
    public static final Index T_AUTH_ROLE_PRIMARY = Indexes0.T_AUTH_ROLE_PRIMARY;
    public static final Index T_AUTH_ROLE_STAFF_MAPPING_IDX_STAFF_ID = Indexes0.T_AUTH_ROLE_STAFF_MAPPING_IDX_STAFF_ID;
    public static final Index T_AUTH_ROLE_STAFF_MAPPING_PRIMARY = Indexes0.T_AUTH_ROLE_STAFF_MAPPING_PRIMARY;
    public static final Index T_AUTH_SYS_IDX_DOMAIN = Indexes0.T_AUTH_SYS_IDX_DOMAIN;
    public static final Index T_AUTH_SYS_PRIMARY = Indexes0.T_AUTH_SYS_PRIMARY;
    public static final Index T_AUTH_SYS_MENU_IDX_PARENT_ID = Indexes0.T_AUTH_SYS_MENU_IDX_PARENT_ID;
    public static final Index T_AUTH_SYS_MENU_IDX_SYS_ID = Indexes0.T_AUTH_SYS_MENU_IDX_SYS_ID;
    public static final Index T_AUTH_SYS_MENU_PRIMARY = Indexes0.T_AUTH_SYS_MENU_PRIMARY;
    public static final Index T_BAMBOO_USER_IDX_UID = Indexes0.T_BAMBOO_USER_IDX_UID;
    public static final Index T_BAMBOO_USER_PRIMARY = Indexes0.T_BAMBOO_USER_PRIMARY;
    public static final Index T_STAFF_IDX_EMAIL = Indexes0.T_STAFF_IDX_EMAIL;
    public static final Index T_STAFF_IDX_PHONE = Indexes0.T_STAFF_IDX_PHONE;
    public static final Index T_STAFF_IDX_UID = Indexes0.T_STAFF_IDX_UID;
    public static final Index T_STAFF_PRIMARY = Indexes0.T_STAFF_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index T_ACCOUNT_PLATFORM_IDX_PLATFORM_ID = Internal.createIndex("idx_platform_id", TAccountPlatform.T_ACCOUNT_PLATFORM, new OrderField[] { TAccountPlatform.T_ACCOUNT_PLATFORM.PLATFORM_ID }, false);
        public static Index T_ACCOUNT_PLATFORM_IDX_UID = Internal.createIndex("idx_uid", TAccountPlatform.T_ACCOUNT_PLATFORM, new OrderField[] { TAccountPlatform.T_ACCOUNT_PLATFORM.UID }, false);
        public static Index T_ACCOUNT_PLATFORM_PRIMARY = Internal.createIndex("PRIMARY", TAccountPlatform.T_ACCOUNT_PLATFORM, new OrderField[] { TAccountPlatform.T_ACCOUNT_PLATFORM.ID }, true);
        public static Index T_ACCOUNT_USER_IDX_EMAIL = Internal.createIndex("idx_email", TAccountUser.T_ACCOUNT_USER, new OrderField[] { TAccountUser.T_ACCOUNT_USER.EMAIL }, false);
        public static Index T_ACCOUNT_USER_IDX_PHONE = Internal.createIndex("idx_phone", TAccountUser.T_ACCOUNT_USER, new OrderField[] { TAccountUser.T_ACCOUNT_USER.PHONE }, false);
        public static Index T_ACCOUNT_USER_IDX_USER_NAME = Internal.createIndex("idx_user_name", TAccountUser.T_ACCOUNT_USER, new OrderField[] { TAccountUser.T_ACCOUNT_USER.USER_NAME }, false);
        public static Index T_ACCOUNT_USER_PRIMARY = Internal.createIndex("PRIMARY", TAccountUser.T_ACCOUNT_USER, new OrderField[] { TAccountUser.T_ACCOUNT_USER.ID }, true);
        public static Index T_AUTH_ITEM_IDX_SYS_MENU = Internal.createIndex("idx_sys_menu", TAuthItem.T_AUTH_ITEM, new OrderField[] { TAuthItem.T_AUTH_ITEM.SYS_ID, TAuthItem.T_AUTH_ITEM.MENU_ID }, false);
        public static Index T_AUTH_ITEM_PRIMARY = Internal.createIndex("PRIMARY", TAuthItem.T_AUTH_ITEM, new OrderField[] { TAuthItem.T_AUTH_ITEM.ID }, true);
        public static Index T_AUTH_ROLE_PRIMARY = Internal.createIndex("PRIMARY", TAuthRole.T_AUTH_ROLE, new OrderField[] { TAuthRole.T_AUTH_ROLE.ID }, true);
        public static Index T_AUTH_ROLE_STAFF_MAPPING_IDX_STAFF_ID = Internal.createIndex("idx_staff_id", TAuthRoleStaffMapping.T_AUTH_ROLE_STAFF_MAPPING, new OrderField[] { TAuthRoleStaffMapping.T_AUTH_ROLE_STAFF_MAPPING.STAFF_ID }, false);
        public static Index T_AUTH_ROLE_STAFF_MAPPING_PRIMARY = Internal.createIndex("PRIMARY", TAuthRoleStaffMapping.T_AUTH_ROLE_STAFF_MAPPING, new OrderField[] { TAuthRoleStaffMapping.T_AUTH_ROLE_STAFF_MAPPING.ID }, true);
        public static Index T_AUTH_SYS_IDX_DOMAIN = Internal.createIndex("idx_domain", TAuthSys.T_AUTH_SYS, new OrderField[] { TAuthSys.T_AUTH_SYS.SYS_DOMAIN }, false);
        public static Index T_AUTH_SYS_PRIMARY = Internal.createIndex("PRIMARY", TAuthSys.T_AUTH_SYS, new OrderField[] { TAuthSys.T_AUTH_SYS.ID }, true);
        public static Index T_AUTH_SYS_MENU_IDX_PARENT_ID = Internal.createIndex("idx_parent_id", TAuthSysMenu.T_AUTH_SYS_MENU, new OrderField[] { TAuthSysMenu.T_AUTH_SYS_MENU.PARENT_ID }, false);
        public static Index T_AUTH_SYS_MENU_IDX_SYS_ID = Internal.createIndex("idx_sys_id", TAuthSysMenu.T_AUTH_SYS_MENU, new OrderField[] { TAuthSysMenu.T_AUTH_SYS_MENU.SYS_ID }, false);
        public static Index T_AUTH_SYS_MENU_PRIMARY = Internal.createIndex("PRIMARY", TAuthSysMenu.T_AUTH_SYS_MENU, new OrderField[] { TAuthSysMenu.T_AUTH_SYS_MENU.ID }, true);
        public static Index T_BAMBOO_USER_IDX_UID = Internal.createIndex("idx_uid", TBambooUser.T_BAMBOO_USER, new OrderField[] { TBambooUser.T_BAMBOO_USER.UID }, false);
        public static Index T_BAMBOO_USER_PRIMARY = Internal.createIndex("PRIMARY", TBambooUser.T_BAMBOO_USER, new OrderField[] { TBambooUser.T_BAMBOO_USER.ID }, true);
        public static Index T_STAFF_IDX_EMAIL = Internal.createIndex("idx_email", TStaff.T_STAFF, new OrderField[] { TStaff.T_STAFF.EMAIL }, false);
        public static Index T_STAFF_IDX_PHONE = Internal.createIndex("idx_phone", TStaff.T_STAFF, new OrderField[] { TStaff.T_STAFF.PHONE }, false);
        public static Index T_STAFF_IDX_UID = Internal.createIndex("idx_uid", TStaff.T_STAFF, new OrderField[] { TStaff.T_STAFF.UID }, false);
        public static Index T_STAFF_PRIMARY = Internal.createIndex("PRIMARY", TStaff.T_STAFF, new OrderField[] { TStaff.T_STAFF.ID }, true);
    }
}
