/*
 * This file is generated by jOOQ.
*/
package com.luzhiqing.bamboo.entity;


import com.luzhiqing.bamboo.entity.tables.*;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in bamboo_auth
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 第三方用户信息
     */
    public static final T_ACCOUNT_PLATFORM T_ACCOUNT_PLATFORM = com.luzhiqing.bamboo.entity.tables.T_ACCOUNT_PLATFORM.T_ACCOUNT_PLATFORM;

    /**
     * 账户
     */
    public static final T_ACCOUNT_USER T_ACCOUNT_USER = com.luzhiqing.bamboo.entity.tables.T_ACCOUNT_USER.T_ACCOUNT_USER;

    /**
     * 系统权限
     */
    public static final T_AUTH_ITEM T_AUTH_ITEM = com.luzhiqing.bamboo.entity.tables.T_AUTH_ITEM.T_AUTH_ITEM;

    /**
     * 员工角色
     */
    public static final T_AUTH_ROLE T_AUTH_ROLE = com.luzhiqing.bamboo.entity.tables.T_AUTH_ROLE.T_AUTH_ROLE;

    /**
     * 权限角色与员工关系
     */
    public static final T_AUTH_ROLE_STAFF_MAPPING T_AUTH_ROLE_STAFF_MAPPING = com.luzhiqing.bamboo.entity.tables.T_AUTH_ROLE_STAFF_MAPPING.T_AUTH_ROLE_STAFF_MAPPING;

    /**
     * 系统map(登记目前存在的后台系统信息)
     */
    public static final T_AUTH_SYS T_AUTH_SYS = com.luzhiqing.bamboo.entity.tables.T_AUTH_SYS.T_AUTH_SYS;

    /**
     * 系统menu
     */
    public static final T_AUTH_SYS_MENU T_AUTH_SYS_MENU = com.luzhiqing.bamboo.entity.tables.T_AUTH_SYS_MENU.T_AUTH_SYS_MENU;

    /**
     * 账户信息
     */
    public static final T_BAMBOO_USER T_BAMBOO_USER = com.luzhiqing.bamboo.entity.tables.T_BAMBOO_USER.T_BAMBOO_USER;

    /**
     * 员工信息(这里列了大概的信息，多的可以垂直拆表)
     */
    public static final T_STAFF T_STAFF = com.luzhiqing.bamboo.entity.tables.T_STAFF.T_STAFF;
}
